### ISSUE TITLE
Find and add an specific font

### ISSUE THREAD

**Issue by Slayer95** [flagrow/fonts#1]
I see no way to register an already known font.
Instead, I have to scroll over an endless list of fonts until finding the one I want.

Am I missing something? I guess this feature would *not* actually require a Google Fonts API key?
I suppose I could always install the font with ``@font-face`` in the forum custom CSS...

**Comment by clarkwinkelmann** [comment]
>  I suppose I could always install the font with `@font-face` in the forum custom CSS...

Yes you can totally do that. The API key is needed to display the full list of fonts in the admin panel, Google won't let us access its API without a key, even for that. Maybe we could embed a key created by Flagrow in there but I'm not sure if that's allowed by Google.

You're totally right about the missing search feature. This is one of the first things to add in the next release :wink: 

PS: as a workaround you can click the load more button until all ~800 fonts are displayed and then use CTRL+F in the page :sweat_smile: not optimal but it works

**Comment by clarkwinkelmann** [comment]
Released `0.1.1` which adds search :wink: 

![image](https://user-images.githubusercontent.com/5264300/28680082-832dff94-72f5-11e7-8f3f-dfa1d9c803a2.png)

**Comment by luceos** [comment]
That's cool 👍
