### ISSUE TITLE
Broken in 0.1.0-beta.7 of flarum

### ISSUE THREAD

**Issue by vbasky** [flagrow/fonts#2]
When I enable with Google API Font Extension and come back its broken

<img width="616" alt="screen shot 2017-10-19 at 6 46 31 pm" src="https://user-images.githubusercontent.com/287302/31759694-f17fbac4-b4fd-11e7-92a1-96ae6faee817.png">

**Comment by luceos** [comment]
- Flarum version 0.1.0-beta.7?
- Did you run `php flarum cache:clear`?
- Did you clear your browser cache?
- Any specific errors in the browser console (if you are able to open that)?
- Do you use cloudflare and clear its cache?
- Any errors in `storage/logs/flarum.log` (ignore the NotFound errors).

**Comment by vbasky** [comment]
It wasn't taking in the Google API Font keys properly. I fed the key. Now no error but the font is not applying. Its still defaulting to Open Sans

**Comment by luceos** [comment]
Do you have a link to the website? And can you please answer the questions from before please 👍

**Comment by vbasky** [comment]
<img width="1275" alt="screen shot 2017-10-19 at 7 07 26 pm" src="https://user-images.githubusercontent.com/287302/31760621-059bff7e-b501-11e7-98da-226ca6452e1b.png">
<img width="1277" alt="screen shot 2017-10-19 at 7 07 54 pm" src="https://user-images.githubusercontent.com/287302/31760622-05ccc47e-b501-11e7-9048-acf28cc659a9.png">

I haven't deployed the application yet. So its not hosted as it was mentioned as beta software. 

storage/logs/flarum.log

https://pastebin.com/5JpBT88T

**Comment by luceos** [comment]
This is not the way this extension works. The extension allows you to include a Font. Using them inside your forum is done either by using the bbcode as the documentation suggests:

```
[font=Fresca]Hello World[/font]
```

Or by using custom css you can configure in the admin area. That also works because the font is included globally in your page.

**Comment by vbasky** [comment]
Working as expected.
